trigger:
  branches:
    include:
    - main

resources:
  repositories:
    - repository: templates
      type: git
      name: Plumbing/core-templates
    - repository: moodle-mod_proctorio
      type: git
      name: Open/moodle-mod_proctorio

stages:
- template: stages/sync/sync.yml@templates  # Template reference
  parameters:
    checkout: moodle-mod_proctorio
